### ISSUE TITLE
Missing RemoteSettings.plist

### ISSUE THREAD

**Issue by dennisgove** [loudnate/xDripG5#1]
When I import this project into xCode I see error 
```
/Users/dennis/dev/xDripG5/xDripG5/RemoteSettings.plist:0: error: reading data: The file “RemoteSettings.plist” couldn’t be opened because there is no such file.
```

Should this file be included in the repo or is it a user-specific file?

**Comment by dennisgove** [comment]
From DiagnosticLogger it appears that the only settings in this file are APIHost, APIKey, and APIPath and that values of "" are acceptable. But also, .gitignore indicates that these values are sensitive and related to remote backup.

**Comment by loudnate** [comment]
Hey Dennis,

Yes, I intend to delete the logger from the example app before releasing
the first version of the framework. For now you should simply be able to
delete the file reference from Xcode and the code can compile without it.

**Comment by dennisgove** [comment]
Great, thanks. 

Btw, I've had the little test app running on my phone since early Tues morning and it has perfectly tracked the values the dexcom app is giving me. Kudos! Tonight I'm gonna start work on a little app for myself using this.
