### ISSUE TITLE
Passive mode working intermittently with version 1.0.19

### ISSUE THREAD

**Issue by loudnate** [loudnate/xDripG5#10]
It looks like a time read doesn't happen during every cycle anymore. I'm seeing a lot of `ControlError("Error waiting for time response: Timeout")` occurrences.

**Comment by loudnate** [comment]
Maybe the app update is just a red herring. Running with #9 (and making sure my old transmitter was on the other end of the house) seemed to help.

**Comment by dennisgove** [comment]
I just saw a missed value. Is it possible the transmitter is cycling some value leading there lib to not know its coming from the transmitter?

**Comment by loudnate** [comment]
Does the missed entry appear in the Dexcom app, but not your app?

**Comment by dennisgove** [comment]
It did. I only missed one, though. Have gotten 4 in a row now. Am running in low power mode, however.

**Comment by dennisgove** [comment]
Also am at a bar filled with people watching the Patriots game so there might've been interference.

**Comment by loudnate** [comment]
Yeah I think my issues were entirely related to the library finding two transmitters and not properly handling that case.
