### ISSUE TITLE
CRC function

### ISSUE THREAD

**Issue by hackingtype1** [loudnate/xDripG5#21]
If you'd like to calculate CRC for messages, this should work:
`static func calculateCRC(byte: UInt8) -> UInt16` 
`{`
` `` ``var crc : UInt16 = 0x00;`
` `` ``var x = crc >> 8 ^ UInt16(byte)`
` `` ``x ^= x>>4`
` `` ``return (crc << 8) ^ (UInt16(x << 12)) ^ (UInt16(x << 5)) ^ (UInt16(x))`
 `}`

**Comment by loudnate** [comment]
Thank you! I was too lazy to figure this out, especially since verifying a CRC for a Bluetooth characteristic value is itself redundant. :-)

**Comment by hackingtype1** [comment]
:-)

**Comment by hackingtype1** [comment]
separate question (I can move to another place to chat if you want), have you played with TX opcode 46, (RX 47) at all? Appears to be sensor data, both filtered and unfiltered values, if I'm not misreading them entirely. I'm verifying now, but I can shoot a pull request your way if you have interest in adding it. I know a lot of folks love the raw data (me included!); unsure if it continues to report during startup, but I will test that today.

**Comment by dennisgove** [comment]
I would love the raw data.

**Comment by loudnate** [comment]
You'll need to calculate the CRC for messages longer than 1-byte for things like calibration. Looking back at my captures, this is the CRC being used: http://web.mit.edu/6.115/www/amulet/xmodem.htm
