### ISSUE TITLE
When switching to a new transmitter, stop restoring the first one

### ISSUE THREAD

**Issue by loudnate** [loudnate/xDripG5#8]
`BluetoothManager` only assumes there's one peripheral we care about, which isn't true as we continue to restore the original one.

In the interest of reusing `BluetoothManager` in other use cases and projects, let's always ask the delegate (in this case, the `Transmitter` class) for permission before connecting.

**Comment by dennisgove** [comment]
Will this result in asking the user for permission?

**Comment by loudnate** [comment]
The user has already provided a `TransmitterID`, but we're not using to differentiate peripherals during scan or restore.

**Comment by dennisgove** [comment]
Ok. I was wondering if asking the transmitter for permission would result in having to ask the user permission for the app to access Bluetooth. I wouldn't want to have to repeat that popup request to the user.

**Comment by loudnate** [comment]
Oh, sorry, you definitely have to do that. It's a new peripheral.

**Comment by loudnate** [comment]
that is, if you're not running in "passive mode", in which case you've already responded to that dialog in the Dexcom app.

**Comment by dennisgove** [comment]
I see. What's the use case for " continue to restore the original one"?

I only ever use in passive mode so suspect I'm missing something here.

**Comment by loudnate** [comment]
`CoreBluetooth` supports something called State Restoration which makes it quicker to re-launch your app in response to bluetooth events, if it was closed for reasons like memory pressure. When the app relaunches and state is restored, you receive a list of all previously connected (or connection-pending) peripherals from the time the app was terminated.

So my first G5 Transmitter went dead yesterday, and I opened a new one, but the library wasn't accounting for having more than one peripheral in its restoration array, and would choose the last one each time. This meant spotty readings until I realized the issue. PR incoming...

**Comment by loudnate** [comment]
@dennisgove Have you updated to the latest version of the Dexcom G5 app?

**Comment by dennisgove** [comment]
I updated to 1.0.19 earlier today and haven't seen any issues in glucose-badge, but I haven't been watching consistently.

**Comment by loudnate** [comment]
I filed #10 to track. I'm seeing successful updates happening only every 30 minutes or so in my app, but the dex app seems to be getting every reading.
